baseurl = "/"
title = "mssht"
languageCode = "en-us"

[caches]
[caches.images]
dir = ':cacheDir/images'

[Pagenation]
pagerSize = "10" # Number of posts per page

[Params]
description = "mssht's Personal blog." # Site description. Used in meta description
copyright = "mssht" # Footer copyright holder, otherwise will use site title
opengraph = true # Enable OpenGraph if true
schema = true # Enable Schema
twitter_cards = false # Enable Twitter Cards if true
readmore = true # Show "Read more" button in list if true
authorbox = true # Show authorbox at bottom of pages if true
toc = true # Enable Table of Contents
pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
mainSections = ["tech", "life", "news"] # Specify section pages to show on home page and the "Recent articles" widget
dateformat = "2006-01-02" # Change the format of dates
mathjax = true # Enable MathJax
mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
# customCSS = ["css/custom.css"] # Include custom CSS files
# customJS = ["js/custom.js"] # Include custom JS files

# DEPRECATED PARAMS
subtitle = "" # Deprecated in favor of .Site.Params.logo.subtitle
highlightColor = "" # Deprecated in favor of .Site.Params.style.vars.highlightColor

[Params.author] # Used in authorbox
name = "mssht"
bio = "A software developer in Tokyo, Japan. Views/opinions here are my own."
avatar = "img/avatar.png"

[Params.style.vars]
highlightColor = "#00cc66" # Override highlight color

# Override font-family sets
# Take care of different quotes OR escaping symbols in these params if necessary
fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
# Secondary font-family set responsible for pre, code, kbd, and samp tags font
fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.logo]
# image = "favicon.ico" # Logo image. Path relative to "static"
title = "mssht" # Logo title, otherwise will use site title
subtitle = "mssht's personal blog" # Logo subtitle

[Params.thumbnail]
visibility = ["list", "post"] # Control thumbnail visibility

[Params.sidebar]
home = "right" # Configure layout for home page
list = "left"  # Configure layout for list pages
single = false # Configure layout for single pages
# Enable widgets in given order
widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
recent_num = 5 # Set the number of articles in the "Recent articles" widget
categories_counter = true # Enable counter for each category in "Categories" widget
tags_counter = true # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
cached = false # activate cache if true
# Enable parts of social widget
simplex = 'https://smp12.simplex.im/a#IQ0Ih0p9HMqk7fQE4_qwpoytOfFqMXG18oS5uQ4ugsA'
github = "msshtdev"
email = "dev.msshta@proton.me"

[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "rss"
url = "/index.xml"
weight = 2

[[menu.main]]
name = "gpg"
url = "/gpg-key.txt"
weight = 3

[outputs]
home = ["html", "json", "rss"]
